happy = Mood.create(state: "Happy")
angry = Mood.create(state: "Angry")
humorous = Mood.create(state: "Humorous")
anxious = Mood.create(state: "Anxious")
calm = Mood.create(state: "Calm")
fearful = Mood.create(state: "Fearful")
hopeful = Mood.create(state: "Hopeful")
sad = Mood.create(state: "Sad")

# prommpt = Prompt.create(desc: "Graduating from school", mood_id: 1, controllable: true)