happy = Mood.create(feeling: "Happy")
angry = Mood.create(feeling: "Angry")
humorous = Mood.create(feeling: "Humorous")
anxious = Mood.create(feeling: "Anxious")
calm = Mood.create(feeling: "Calm")
fearful = Mood.create(feeling: "Fearful")
hopeful = Mood.create(feeling: "Hopeful")
sad = Mood.create(feeling: "Sad")